### ISSUE TITLE
1st playtest, scheduled for Tuesday, June 5, 2018.

### ISSUE THREAD

**Issue by blinks** [blinks/18xplore#4]
Good:
- Plays just fine! Feels 18xx-y.
- $400 starting cash is good
- Current tiles seem fine, though the capital is perhaps too symmetric: the first guild house is a non-decision: #1 
- Tile locations should have names.
- 22 tiles seems good, but we didn't play long enough to know for sure.
- $10, $20, $30, ... exploration is good.
- Place at most one tile for each active route is good.
- 1846 stock growth (and chart) is good.

Bad:
- Hard for a non 18xx-er to get started on strategy.
- Blank "company cards" meant no real decision there.
- Couldn't hold potentials back: need chunked stock release, like Poseidon. Company cards might force the initial release (and provide fixed starting funds): #3, #2.
- Selling shares should just go to the bank, which can be on the stock price tracker board. No reason to get fancy with the potentials.
- Resolving expedition retirement is a bit slow.
- Dice are annoying for expeditions; make tokens.

**Comment by blinks** [comment]
Images from the playtest: https://photos.app.goo.gl/ayRSBQYEngRoZCH82

**Comment by garykac** [comment]
Positive:
* Paths on hexes worked really well, esp with the crossover to keep the paths somewhat mixed together
* Liked the station decision WRT the Fuji Flush grouping of the stations to determine the one that gets "rust"ed out.

Negative:
* The tiles with the long straight paths across the hex allow players to escape the twisty interaction. Is this good? I don't know. As it is, it's a useful strategy for breaking out, but that pulls players into solo play.
* Concern that the Fuji Flush grouping will be hard to describe.
* Buying the last stock means that you can't expand anymore. Not sure if this is negative or not.

**Comment by blinks** [comment]
- Escaping the interaction: at the moment, I think that it gives the game texture. Unless everyone's able to escape (and wants to do so), there's information there for investment decision-making.
- Fuji Flush rust: certainly worried. I love the effect, though. Something to keep an eye on.
- Stock controlling expansions: I've ordered a bunch more "potentials" discs, so we can try various amounts, and company card restrictions will make this a bit easier to control in the future. I think the biggest problem with potentials in today's game is that of _course_ you wanted to buy, and with only four companies, we bought them out too quickly.
